server.port=8080
spring.application.name=TheHive
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
logging.level.org.example=DEBUG
